language: node_js
node_js: lts/*
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
- yarn install
- yarn add firebase-ci@0.4.6 # install firebase-ci for use in creating config and deploying
script:
- yarn build
- yarn test
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
    message: "Delpoying to Firebase"