language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
before_install:
  - npm install -g firebase-tools@5.0.0
  - npm install
script:
  - npm test
after_success:
  - npm run build
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master